/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xfhy_jnihelloworld_MainActivity */

#ifndef _Included_com_xfhy_jnihelloworld_MainActivity
#define _Included_com_xfhy_jnihelloworld_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xfhy_jnihelloworld_MainActivity
 * Method:    helloFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_xfhy_jnihelloworld_MainActivity_helloFromC
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
