/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xfhy_pressuredemo_MainActivity */

#ifndef _Included_com_xfhy_pressuredemo_MainActivity
#define _Included_com_xfhy_pressuredemo_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xfhy_pressuredemo_MainActivity
 * Method:    startPressure
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xfhy_pressuredemo_MainActivity_startPressure
  (JNIEnv *, jobject);

/*
 * Class:     com_xfhy_pressuredemo_MainActivity
 * Method:    stopPressure
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xfhy_pressuredemo_MainActivity_stopPressure
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
