/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xfhy_jnicfork_MainActivity */

#ifndef _Included_com_xfhy_jnicfork_MainActivity
#define _Included_com_xfhy_jnicfork_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xfhy_jnicfork_MainActivity
 * Method:    cfork
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xfhy_jnicfork_MainActivity_cfork
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
